#!/system/bin/sh
port_on="5555"
port_off="-1"
prop="service.adb.tcp.port"
service="adbd"

port="$port_off"

if [ ! -z "$1" ]; then
	port="$1"

	if [ ! -z "$(echo $port | grep -i on)" ]; then
		port="$port_on"
	fi

	if [ ! -z "$(echo $port | grep -i off)" ]; then
		port="$port_off"
	fi

	if [ ! -z "$(echo $port | grep -E '^-?[0-9]+$')" ]; then
		setprop "$prop" "$port"
		stop "$service"
		start "$service"
	fi
fi

getprop | grep "$prop"

